# Jekyll config
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

highlighter: pygments

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

# Site configuration
permalink: /:categories/:year/:month/:day/:title
production_url: http://www.gedge.ca/

# Site data
title: Jason Gedge
author:
    name: Jason Gedge
    github: thegedge
    twitter: thegedge

