exclude:
  - .bundle
  - README.md
  - Gemfile
  - Gemfile.lock

permalink: /:categories/:year/:month/:day/:title
url: http://www.gedge.ca
baseurl: ''
environment: production

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

collections:
  presentations:
    output: true
    permalink: /presentations/:path

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: presentations
    values:
      layout: presentation
      presentation:
        separators:
          slide: "<hr />"
          notes: "<p>Notes:</p>"

# Site data
title: Jason Gedge
author:
  name: Jason Gedge
  github: thegedge
  twitter: thegedge

gems:
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-paginate
