# Jekyll config
exclude:
  - .rvmrc
  - .rbenv-version
  - changelog.md
  - Rakefile
  - README.md
  - vendor/bundle

highlighter: pygments

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

# Site configuration
permalink: /:categories/:year/:month/:day/:title
url: http://www.gedge.ca
baseurl:

# Site data
title: Jason Gedge
author:
    name: Jason Gedge
    github: thegedge
    twitter: thegedge

gems:
  - jekyll-feed
