# Jekyll config
exclude:
  - .bundle
  - README.md
  - Gemfile
  - Gemfile.lock

# Site configuration
permalink: /:categories/:year/:month/:day/:title
url: http://www.gedge.ca
baseurl: ''

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

# Site data
title: Jason Gedge
author:
  name: Jason Gedge
  github: thegedge
  twitter: thegedge

gems:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-paginate
